### ISSUE TITLE
- [ ] Definir los servicios del Backend que se deben implementar de acuerdo con las reglas de negocio. (Objeto JSON)

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sn_ppi2020#17]

**Comment by JohnFlorez25** [comment]
@ju-diego @juanlopez12 @CarlosMario639 El siguiente formato se especifica la estructura de como deben evidenciar cada uno de los servicios backend que van a ser consumidos desde el frontend
[Formato Definición de los servicios backend.docx](https://github.com/JohnFlorez25/equipo6_sn_ppi2020/files/5301345/Formato.Definicion.de.los.servicios.backend.docx)

**Comment by ju-diego** [comment]
@JohnFlorez25 esta actividad ya se encuentra en la wiki para ser revisada y cerrada. Gracias

**Comment by JohnFlorez25** [comment]
@ju-diego Listo, revisado y aprobado
