### ISSUE TITLE
- [ ] Construcción de la BD haciendo uso de MySQL

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo6_sn_ppi2020#19]

**Comment by ju-diego** [comment]
Terminación base de datos en Clever cloud y mysqul. Listo para ser revisada

**Comment by ju-diego** [comment]
Además del script ya estar montado https://github.com/JohnFlorez25/equipo6_sn_ppi2020/blob/master/BD/SCRIPTBD.txt
@JohnFlorez25 @jennymontoya1001
